### ISSUE TITLE
Add Cartoon Image models

### ISSUE THREAD

**Issue by parth-verma7** [ashut0sh75/Cartoon#1]
@ashut0sh75 I would like to add VToonify model to it.
VToonify is an open-source model that cartoon images of different kinds like
Cartoon-Beautiful, Cartoon-Princess, Cartoon-Big Eyes, Cartoon, Masculine, Cartoon-Handsome.

Along with it we can create Illustration, Arcane and Comic images as well.

**Comment by ashut0sh75** [comment]
Hi @parth-verma7,

Thank you for taking the time to open this issue in our project! We appreciate your contribution and effort to improve our project. I've reviewed the issue, and we would like to accept it.

If you have any questions or need further clarification, please don't hesitate to ask. We encourage you to submit a pull request to address this issue, and we're here to assist you throughout the process.

Once again, thank you for your contribution to our project. We look forward to collaborating with you to resolve this issue.

### Please star our repository.

Best regards,
@ashut0sh75

**Comment by parth-verma7** [comment]
> Hi @parth-verma7,
> 
> Thank you for taking the time to open this issue in our project! We appreciate your contribution and effort to improve our project. I've reviewed the issue, and we would like to accept it.
> 
> If you have any questions or need further clarification, please don't hesitate to ask. We encourage you to submit a pull request to address this issue, and we're here to assist you throughout the process.
> 
> Once again, thank you for your contribution to our project. We look forward to collaborating with you to resolve this issue.
> 
> ### Please star our repository.
> Best regards, @ashut0sh75

@ashut0sh75  Can you please make this issue labelled as hacktoberfest

**Comment by ashut0sh75** [comment]
@parth-verma7 Please star our repository to make sure other developer also get a chance to contribute. Thank you.

**Comment by Maan-Sharma** [comment]
Can I work on this ?

**Comment by ashut0sh75** [comment]
Sorry, @Maan-Sharma we appreciate your enthusiasm to contribute but this issue has already been assigned to @parth-verma7 but you can always create a new issue to contribute to the project if it passed our standards, it will definitely be merged in the project.
We again thank you for taking your time to look into our project. Please Star our repository.

**Comment by ashut0sh75** [comment]
There is new issue from our side @Maan-Sharma, if you would like to contribute to it. 
Thank You.

**Comment by Maan-Sharma** [comment]
yeha,Sure @ashut0sh75

**Comment by ashut0sh75** [comment]
Hi @parth-verma7 This message is to remind you that your issue has been open for over 2 weeks now and there is no update from your side this is barring other contributors to contribute in our project. So, we have decided to either close this issue after 24 hours of this message or will be assigned to someone else. For now we are removing hacktoberfest label from it.
