### ISSUE TITLE
Update the .gitignore file 

### ISSUE THREAD

**Issue by lingarajsankaravelu** [ashut0sh75/Cartoon#10]
Avoids contributors from committing unnecessary files back to this repository. The current .gitignore file doesn't handle this very well. An example can be found here.[ Android.gitignore](https://github.com/github/gitignore)

**Comment by ashut0sh75** [comment]
Ok sure, We are assigning this issue to you. 

### Please do not forget to star our repository.

**Comment by lingarajsankaravelu** [comment]
@ashut0sh75 . Just wanted report you can assign this to someone else.

**Comment by ashut0sh75** [comment]
Ok no problem.

**Comment by lingarajsankaravelu** [comment]
@ashut0sh75 No problem I will pick it up.

**Comment by ashut0sh75** [comment]
So do you want me to assign it to you.

**Comment by lingarajsankaravelu** [comment]
@ashut0sh75 yes.

**Comment by ashut0sh75** [comment]
Thank @lingarajsankaravelu for your contribution. We would really like to have more from you. We hope to hear from you soon.

### Please star our repository. This will help us in increasing our reach.
