### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by ashut0sh75** [ashut0sh75/Cartoon#2]
We really want to improve our UI to make it more attractive. An interactive splash screen, buttons, and Image View are some of the areas we want to improve.

**Comment by Maan-Sharma** [comment]
Hey, I can add the all stuff  if  you want @ashut0sh75

**Comment by Maan-Sharma** [comment]
And Also Can You add Hacktoberfest label on it.

**Comment by ashut0sh75** [comment]
Good Luck @Maan-Sharma . This issue has been assigned to you.

**Comment by ashut0sh75** [comment]
Please Star our repository to help other contributors to contribute in our project.

**Comment by Maan-Sharma** [comment]
Hey, Can you provide me the image for Splash_screen

**Comment by Maan-Sharma** [comment]
or I add by My choice @ashut0sh75

**Comment by ashut0sh75** [comment]
you can add of your choice.

**Comment by Maan-Sharma** [comment]
hey, I created sp_Screen and also I made a PR @ashut0sh75

**Comment by ashut0sh75** [comment]
Yes we reviewed it and merged it. Thank you for your contribution. 
Please Star our repository.

**Comment by Maan-Sharma** [comment]
hey can I add gradient btn and change the background color or add a image to back ground @ashut0sh75

**Comment by ashut0sh75** [comment]
yes please. Make sure that you make a dynamic background with cool buttons and also make toasts messages more fancy and also improve the title of the page with much attractive graphics and add dark mode and light mode button also you can improve the image view a lot.

**Comment by AdityaKumdale** [comment]
Made Some UI enhancements on Buttons , requesting permission @ashut0sh75 for pull request as per project rules.

**Comment by ashut0sh75** [comment]
Sorry @AdityaKumdale, although we appreciate your enthusiasm to contribute in our project but this issue has already been assigned to @Maan-Sharma. For this reason we cannot accept your PR in this issue but you can make a new issue and that issue will be assigned to you then we will consider your PR and review it.

Thank you for choosing our project.

**Comment by Maan-Sharma** [comment]
![WhatsApp Image 2023-10-08 at 9 34 56 PM](https://github.com/ashut0sh75/Cartoon/assets/146059379/4f7268ac-2000-463c-a0ea-84d9d16ca6fb)
![WhatsApp Image 2023-10-08 at 9 34 56 PM (1)](https://github.com/ashut0sh75/Cartoon/assets/146059379/20d87199-8a28-4bc1-a8dc-19148025253a)

**Comment by Maan-Sharma** [comment]
The Light Ui
![WhatsApp Image 2023-10-08 at 9 34 55 PM](https://github.com/ashut0sh75/Cartoon/assets/146059379/9941a547-3dff-4781-8421-0e4994618d39)

**Comment by Maan-Sharma** [comment]
The Dark Mode UI
![WhatsApp Image 2023-10-08 at 9 34 55 PM](https://github.com/ashut0sh75/Cartoon/assets/146059379/97af4b67-4825-4fe5-b1e3-213daca161be)

**Comment by ashut0sh75** [comment]
Thank you @Maan-Sharma for your amazing contribution in out project. Since there have been many updates in our UI, we will now be focusing on our backend. For that reason we are closing this issue. 

Thank you again.
