### ISSUE TITLE
The selected image doesn't fits properly in the imageview🐞🐞

### ISSUE THREAD

**Issue by vinitfreakk** [ashut0sh75/Cartoon#22]
after clicking the save image button it always shows no image selected before showing the image saved toast.

![WhatsApp Image 2023-10-15 at 22 42 58](https://github.com/ashut0sh75/Cartoon/assets/100133057/d305cb50-65d7-4bfa-8c4f-4eab1dbc418f)
![WhatsApp Image 2023-10-15 at 22 42 58 (2)](https://github.com/ashut0sh75/Cartoon/assets/100133057/5d46258c-8282-4c2b-80c5-eea1e6205134)

**Comment by ashut0sh75** [comment]
ok we are assigning you this task.

**Comment by ashut0sh75** [comment]
Thank you for your contribution @vinitfreakk.
