### ISSUE TITLE
Add some Github workflow Actions. 

### ISSUE THREAD

**Issue by lingarajsankaravelu** [ashut0sh75/Cartoon#23]
Add the following github workflow actions for pull request and master merge
1. Gradle wrapper validation. 
2. Run lint 
3. build project. 
4. run test. - This can be used for the future.

**Comment by lingarajsankaravelu** [comment]
@ashut0sh75. Can you assign this issue to me.

**Comment by ashut0sh75** [comment]
yes sure.

**Comment by lingarajsankaravelu** [comment]
@ashut0sh75 Can you please add the hacktoberfest label as well.

**Comment by ashut0sh75** [comment]
yup
