### ISSUE TITLE
App Not User-Friendly in Landscape Mode. 

### ISSUE THREAD

**Issue by vinitfreakk** [ashut0sh75/Cartoon#27]
We can either stick to portrait mode only or make it work in landscape mode as well.

![786d496f-660c-47a6-97e4-4f3f459246a8](https://github.com/ashut0sh75/Cartoon/assets/100133057/91498adb-9dfb-4c86-b054-9805238df0ae)

**Comment by ashut0sh75** [comment]
yes but we have decided to be on portrait mode only so what we can do is we can lock the app in portrait mode. If you want to work on it you can, we will assign you.

**Comment by vinitfreakk** [comment]
assign this to me. i will lock it in portrait  mode

**Comment by vinitfreakk** [comment]
I've fixed the issue🥷🥷

**Comment by ashut0sh75** [comment]
Thank you.
