### ISSUE TITLE
Can hide both Status Bar and Navigation Bar💫

### ISSUE THREAD

**Issue by vinitfreakk** [ashut0sh75/Cartoon#28]
Hiding the navigation bar and the Status Bar can provide more cleaner look

![b6b7da25-55ba-4011-8f0f-ea7e5c7f3fb5](https://github.com/ashut0sh75/Cartoon/assets/100133057/bab17a2f-743b-4933-a460-78f8b81cece1)

**Comment by ashut0sh75** [comment]
okk, we are assigning you this.

**Comment by vinitfreakk** [comment]
@ashut0sh75 can you also assign me the hactoberfest tag.

**Comment by vinitfreakk** [comment]
Why did you use a Compose activity to build the app if you wanted it to be created in XML? Is there any specific reason? I mean, you would have chosen an Empty Views activity instead of a Compose activity

**Comment by ashut0sh75** [comment]
No there is no specific reason for them. We can remove them.

**Comment by vinitfreakk** [comment]
okay🥷

**Comment by ashut0sh75** [comment]
This issue has been resolved so we are closing this issue.

Thank you .
