### ISSUE TITLE
can improve the entire app's UI, including the splash screen and toast.

### ISSUE THREAD

**Issue by vinitfreakk** [ashut0sh75/Cartoon#32]

**Comment by ashut0sh75** [comment]
you can improve it. Actually I was thinking to open an issue permanently to improve UI and UX and anyone can propose their ideas.

**Comment by vinitfreakk** [comment]
@ashut0sh75 hope you like the ui 🥷🥷

https://github.com/ashut0sh75/Cartoon/assets/100133057/a61b215f-7adc-4d27-9974-618c1dbb26a2

**Comment by ashut0sh75** [comment]
looking good.

**Comment by vinitfreakk** [comment]
fine will make a pr soon. can you please provide me with the hacktober fest tags😅😅
