### ISSUE TITLE
Update Depreceated onActivityResult 

### ISSUE THREAD

**Issue by lingarajsankaravelu** [ashut0sh75/Cartoon#33]
1. Use ActivityResult API for Selecting Image from device and Permissions.
2. Introduces READ_MEDIA_IMAGES permissions , which is should be used instead of READ_EXTERNAL_STORAGE in android 13+ devices.
3. Cleanup old codes.

**Comment by lingarajsankaravelu** [comment]
@ashut0sh75 . Can you assign this issue to me.

**Comment by ashut0sh75** [comment]
yes sure.

**Comment by ashut0sh75** [comment]
Thank you for contributing.
