### ISSUE TITLE
Code cleanUp

### ISSUE THREAD

**Issue by lingarajsankaravelu** [ashut0sh75/Cartoon#34]
1. Move declared strings under xml and class files to string.xml
2. Move dimension definitions to dimen.xml.
3. Remove unwanted imports and commented out code. 
etc.

**Comment by lingarajsankaravelu** [comment]
@ashut0sh75 Can you please assign this issue to me. Thanks.

**Comment by MJJacobs01** [comment]
Good evening,

Can you assign the issue to me please?

**Comment by ashut0sh75** [comment]
Hi @MJJacobs01,

We truly appreciate your enthusiasm to contribute to our project. However, I must inform you that this particular issue has already been assigned to @lingarajsankaravelu. Nevertheless, please feel free to create a new issue, and we encourage you to request your involvement in it. Thank you for your interest and dedication.

**Comment by ashut0sh75** [comment]
Thank you so much @lingarajsankaravelu .
