### ISSUE TITLE
Viewbinding Implementation

### ISSUE THREAD

**Issue by VedantpD** [ashut0sh75/Cartoon#36]
Am really sorry, I was having my exams. I promise to complete the task by today (or within 4 hours of assigning). Please assign it back to me. @ashut0sh75

**Comment by ashut0sh75** [comment]
okk

**Comment by ashut0sh75** [comment]
Thanks @VedantpD

**Comment by vinitfreakk** [comment]
@ashut0sh75 should we continue??

**Comment by vinitfreakk** [comment]
do you have any ideas??

**Comment by ashut0sh75** [comment]
Yup, I think we need more types of options before deploying to make it more attractive.

Also I am opening a discussion issue to discuss things there. Please move the conversation there.
 Thank you.
