### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ashut0sh75** [ashut0sh75/Cartoon#6]
Make readme more attractive by adding emojis, animations, GIFs, and much more interactive graphics to make it more exciting to read.

**Comment by ayushsarode** [comment]
Can you assign this issue to me?

**Comment by ashut0sh75** [comment]
Yeah Sure.

**Comment by ashut0sh75** [comment]
Good Luck @ayushsarode . Thank you for choosing our repository. Please do not change the content of readme but make it more interactive and attractive. 
 Please star our repository.

**Comment by ayushsarode** [comment]
Sure

**Comment by ayushsarode** [comment]
Do I add steps for contribution and table of content?

**Comment by ashut0sh75** [comment]
yes please.

**Comment by ashut0sh75** [comment]
hi @ayushsarode this issue has been assigned to you for a week now, which is barring other contributors from contributing in it. Please update your status within 24 - hours of this message.

**Comment by ayushsarode** [comment]
> hi @ayushsarode this issue has been assigned to you for a week now, which is barring other contributors from contributing in it. Please update your status within 24 - hours of this message.

I'll make the PR tomorrow!
Sorry for Inconvenience.

**Comment by ashut0sh75** [comment]
Hi @ayushsarode the contribution of yours has been exceptionally delayed, so we have decided to remove you from this PR after 12 hours of this message.

**Comment by ayushsarode** [comment]
Sure!
I'm sorry for Inconvenience, I'm busy in my college studies.

**Comment by ashut0sh75** [comment]
We understand your position and we really wanted you to contribute but as informed you before that it is barring other contributors from contributing and we feel really sad to turn them down so unfortunately, we are forced to do so. If you did not make PR in the given time this issue will be assigned to someone else.

Thank You.

**Comment by Vani177** [comment]
hey @ashut0sh75
I can work on this issue. Please assign it to me.
Thanks!

**Comment by ayushsarode** [comment]
Hey @ashut0sh75 you can assign the issue to @Vani177

**Comment by ashut0sh75** [comment]
Hi @Vani177 we are happy to have you. We are assigning you this issue. Please make sure you do not make any changes in the content but make it attractive as mush as possible. You can use logos, Gifs, animations etc.

Thank you.

**Comment by Vani177** [comment]
> Hi @Vani177 we are happy to have you. We are assigning you this issue.

Glad to contribute~

**Comment by ashut0sh75** [comment]
@Vani177  are you a hacktoberfest contributor ?? Would you like if we add Hactoberfest label on it ??

Please star our repository.

**Comment by Vani177** [comment]
yeah sure!

**Comment by Vani177** [comment]
i've completed my hactoberfest prs already btw, so it's up to you, there's particularly no need of the label

**Comment by ashut0sh75** [comment]
> i've completed my hactoberfest prs already btw, so it's up to you, there's particularly no need of the label

ohh very well then, we still added the label.

**Comment by ashut0sh75** [comment]
We are closing this issue. Thank you for your contribution @Vani177
