### ISSUE TITLE
Add new model and give user option to choose between different styles.

### ISSUE THREAD

**Issue by ashut0sh75** [ashut0sh75/Cartoon#7]
We only has one type of ml model right now, we want to give more option to user to choose between different styles like anime, 3d etc.

**Comment by hith3sh** [comment]
can i have this @ashut0sh75 ? and please add the hacktoberfest label

**Comment by ashut0sh75** [comment]
Hi @hith3sh Thank you choosing our project. We are assigning you this issue.

**Comment by ashut0sh75** [comment]
hi @hith3sh  would you like to share what problem you are facing.

**Comment by ashut0sh75** [comment]
hi @hith3sh  this issue has been assigned to you for a week now, which is barring other contributors from contributing in it. Please update your status within 24 - hours of this message or else you will be unassigned from this issue.

**Comment by hith3sh** [comment]
please do unassign.I caught with some work and couldnt reply sorry

**Comment by ashut0sh75** [comment]
@hith3sh would you like to share your .tflite model with us. I wanna see if I can do something about it ?

**Comment by vinitfreakk** [comment]
What kind of model are you looking to add? Maybe I can give it a try.

**Comment by ashut0sh75** [comment]
@vinitfreakk a machine learning model which can convert images to cartoons. Right now we only have one model which convert the image in one type of style but if we had more models like anime, 3D avatars then we could make it more interesting.

**Comment by vinitfreakk** [comment]
I am not able to find the model's to integrate . can you just help me out.

**Comment by ashut0sh75** [comment]
@vinitfreakk I am also in search for models you can searc image to cartoon ml models on github you will find many project for example search vtoonify github you will see such a project.

**Comment by vinitfreakk** [comment]
@ashut0sh75 fine will look into it.🥷🥷🥷
