### ISSUE TITLE
Implementation of view binding

### ISSUE THREAD

**Issue by VedantpD** [ashut0sh75/Cartoon#8]
This will definitely reduce the boilerplate code and will improve code readability.

**Comment by ashut0sh75** [comment]
Ok this task will be assigned to you.

Please star our repository.

**Comment by ashut0sh75** [comment]
hi @VedantpD this issue has been assigned to you for a week now, which is barring other contributors from contributing in it. Please update your status within 24 - hours of this message.

**Comment by ashut0sh75** [comment]
Hii @VedantpD since we see no update from your side we are closing this issue.
